<?php
function ds_bootstrap_6_6_bricks () {
  return array(
    'label' => t('Bootstrap 6-6 bricks template'),
    'regions' => array(
      'top' => t('Top'),
      'topleft' => t('Upper Left'),
      'topright' => t('Upper Right'),
      'central' => t('Middle'),
      'bottomleft' => t('Lower Left'),
      'bottomright' => t('Lower Right'),
      'bottom' => t('Bottom'),
    ),
    'form' => TRUE,
    'image' => TRUE,
  );

}
